spec:
  containers:
  - name: dind
    image: docker:dind
    imagePullPolicy: IfNotPresent
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /root
      - name: dind-storage-1
        mountPath: /var/lib/docker
  imagePullSecrets:
  - name: harbor-jenkins
  volumes:
  - name: dind-storage-1
    hostPath:
      path: /tmp/1
      type: DirectoryOrCreate
  - name: dind-storage-me
    hostPath:
      path: /tmp/me
      type: DirectoryOrCreate
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: harbor-jenkins
          items:
            - key: .dockerconfigjson
              path: .docker/config.json
