apiVersion: v1
kind: Pod
metadata:
  name: danger
  namespace: jenkins
spec:
  containers:
  - name: danger
    image: docker.calponia-divramod.de/devops/danger:latest
    imagePullPolicy: IfNotPresent
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /root/.docker
        subPath: .docker
    env:
    - name: DANGER_GITHUB_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: ssh-key-jenkins-github-pipeline-testing
          key: deployToken
  imagePullSecrets:
  - name: harbor-jenkins
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: harbor-jenkins
          items:
            - key: .dockerconfigjson
              path: .docker/config.json
