apiVersion: v1
kind: Pod
metadata:
  name: git
  namespace: jenkins
spec:
  containers:
  - name: git
    image: docker.calponia-divramod.de/jenkins/devops/arch:latest
    imagePullPolicy: IfNotPresent
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /root
  imagePullSecrets:
  - name: harbor-jenkins
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: harbor-jenkins
          items:
            - key: .dockerconfigjson
              path: .docker/config.json
