apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-539ddefcae3fd6b411a95982a830d987f4214251
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    # volumeMounts:
      # - name: jenkins-docker-cfg
        # mountPath: /root
  # volumes:
  # - name: jenkins-docker-cfg
    # projected:
      # sources:
      # - secret:
          # name: regcred
          # items:
            # - key: .dockerconfigjson
              # path: .docker/config.json
