apiVersion: v1
kind: Pod
metadata:
  name: dind
  namespace: jenkins
spec:
  containers:
  - name: dind
    image: docker:dind
    imagePullPolicy: IfNotPresent
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /root
      - name: dind-storage
        mountPath: /var/lib/docker
  imagePullSecrets:
  - name: harbor-jenkins
  volumes:
  - name: dind-storage
    emptyDir: {}
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: harbor-jenkins
          items:
            - key: .dockerconfigjson
              path: .docker/config.json
